# Generated by Django 4.2.1 on 2023-06-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_subtotals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotals',
        ),
    ]
